### ISSUE TITLE
Neither npm i @atoy40/indijs nor npm install [-g] @atoy40/indijs is working

### ISSUE THREAD

**Issue by Astrosnoesky1959** [atoy40/indijs#1]
Hello,

When trying to install indijs i get these errors:

npm install [-g] @atoy40/indijs
npm ERR! addLocal Could not install /home/joshua/[-g]
npm ERR! Linux 4.15.0-109-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "[-g]" "@atoy40/indijs"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/joshua/[-g]
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/joshua/[-g]'
npm ERR! enoent ENOENT: no such file or directory, open '/home/joshua/[-g]'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/joshua/npm-debug.log

I attached the log.

Regards,
Joshua

[npm-debug.log](https://github.com/atoy40/indijs/files/4912619/npm-debug.log)

**Comment by atoy40** [comment]
Hello
can you try with a more recent version of node/npm please ?
Anthony.

**Comment by atoy40** [comment]
but it seems you try to install [-g] package ?????
[-g] means -g is an optional arg to install the package globally. Try to remove that [-g] from you command line
Anthony.
